n = input('Diga algo:')
print('o tipo primitivo é', type(n))
print('é um número?', n.isnumeric())
print('é uma palavra', n.isalpha())
print('só tem espacos?', n.isspace())
print('Está em maiusculas', n.isupper())
print('Está em minusculas', n.islower())
print('é decimal?', n.isdecimal())
print('é numero-letra?', n.isalnum())
